//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectInformationManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class incoming_project
    {
        public int temp_project_id { get; set; }

        [DisplayName("Project Name")]
        [Required(ErrorMessage = "Required.")]
        public string project_name { get; set; }

        [DisplayName("PI Name")]
        [Required(ErrorMessage = "Required.")]
        public string lab_head { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "Required.")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Please enter a valid e-mail adress")]
        public string email_id { get; set; }

        [DisplayName("Investigator Name")]
        [Required(ErrorMessage = "Required.")]
        public string contact_name { get; set; }

        [DisplayName("Contact Email")]
        [Required(ErrorMessage = "Required.")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Please enter a valid e-mail adress")]
        public string contact_email { get; set; }

        [DisplayName("Contact Phone")]
        [Required(ErrorMessage = "Required.")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid Phone number")]
        public string contact_phone { get; set; }

        [DisplayName("Sample Type")]
        [Required(ErrorMessage = "Required.")]
        public string sample_type { get; set; }

        [DisplayName("No. Of Samples")]
        [Required(ErrorMessage = "Required.")]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "must be a numeric value")]
        public int number_of_samples { get; set; }

        [DisplayName("Samples With Core")]
        [Required(ErrorMessage = "Required.")]
        public string samples_with_core { get; set; }

        [DisplayName("Species")]
        [Required(ErrorMessage = "Required.")]
        public string species { get; set; }

        [DisplayName("Service Requested")]
        [Required(ErrorMessage = "Required.")]
        public string service_requested { get; set; }

        [DisplayName("Downstream Process")]
        [Required(ErrorMessage = "Required.")]
        public string downstream_process { get; set; }

        [DisplayName("Date Submitted")]
        [Required(ErrorMessage = "Required.")]
        public System.DateTime date_submitted { get; set; }

        [DisplayName("Comments")]
        public string comments { get; set; }
    }
}
