//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectInformationManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class new_project
    {
        public int project_id { get; set; }

        [DisplayName("Project Name")]
        [Required(ErrorMessage = "Required.")]
        public string project_name { get; set; }

        [DisplayName("Investigator Name")]
        [Required(ErrorMessage = "Required.")]
        public string investigator_name { get; set; }

        [DisplayName("PI Name")]
        [Required(ErrorMessage = "Required.")]
        public string lab_head { get; set; }

        [DisplayName("Contact Name")]
        [Required(ErrorMessage = "Required.")]
        public string contact_name { get; set; }

        [DisplayName("Contact Email")]
        [Required(ErrorMessage = "Required.")]
        public string contact_email { get; set; }

        [DisplayName("Contact Phone")]
        [Required(ErrorMessage = "Required.")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid Phone number")]
        public string contact_phone { get; set; }

        [DisplayName("Service Requested")]
        [Required(ErrorMessage = "Required.")]
        public string service_requested { get; set; }

        [DisplayName("Sample Type")]
        [Required(ErrorMessage = "Required.")]
        public string sample_type { get; set; }

        [DisplayName("Species")]
        [Required(ErrorMessage = "Required.")]
        public string species { get; set; }

        [DisplayName("No. Of Samples")]
        [Required(ErrorMessage = "Required.")]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "Must be numeric value")]
        public int number_of_samples { get; set; }

        [DisplayName("Date Submitted")]
        [Required(ErrorMessage = "Required.")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public System.DateTime date_submitted { get; set; }

        [DisplayName("Date Samples Submitted")]
        [Required(ErrorMessage = "Required.")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public System.DateTime date_samples_submitted { get; set; }

        [DisplayName("Current Status")]
        [Required(ErrorMessage = "Required.")]
        public string current_status { get; set; }

        [DisplayName("Date Completed")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> date_completed { get; set; }

        [DisplayName("Downstream Process")]
        public string downstream_process { get; set; }

        [DisplayName("Service Cost")]
        [Required(ErrorMessage = "Required.")]
        [RegularExpression(@"^[1-9]\d*(\.\d+)?$", ErrorMessage = " must be numeric or decimal value")]
        public double service_cost { get; set; }

        [DisplayName("Comments")]
        public string comments { get; set; }
    }
}
