//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectInformationManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pimsEntitiesNew : DbContext
    {
        public pimsEntitiesNew()
            : base("name=pimsEntitiesNew")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<capture_data> capture_data { get; set; }
        public virtual DbSet<extraction_data> extraction_data { get; set; }
        public virtual DbSet<incoming_project> incoming_project { get; set; }
        public virtual DbSet<library_prep> library_prep { get; set; }
        public virtual DbSet<new_project> new_project { get; set; }
        public virtual DbSet<sample_detail> sample_detail { get; set; }
        public virtual DbSet<sequencing_data> sequencing_data { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
