//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectInformationManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class sample_detail
    {
        public int sampleRecordId { get; set; }

        [DisplayName("Project ID")]
        [Required(ErrorMessage = "Required")]
        public int project_id { get; set; }

        [DisplayName("GCL ID")]
        [Required(ErrorMessage = "Required.")]
        public string gcl_id { get; set; }

        [DisplayName("Sample ID")]
        [Required(ErrorMessage = "Required.")]
        public string sample_id { get; set; }
    }
}
