//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectInformationManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sequencing_data
    {
        public int seqRecordId { get; set; }

        [Required(ErrorMessage = " ")]
        public int project_id { get; set; }

        [Required(ErrorMessage = " ")]
        public string gcl_id { get; set; }

        [Required(ErrorMessage = " ")]
        public string sample_id { get; set; }

        [Required(ErrorMessage = " ")]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "no decimal values")]
        public int total_reads { get; set; }

        [Required(ErrorMessage = " ")]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "no decimal values")]
        public int unmapped_reads { get; set; }

        [Required(ErrorMessage = " ")]
        public string qc_status { get; set; }

        [Required(ErrorMessage = " ")]
        public string data_delivered { get; set; }

        [Required(ErrorMessage = " ")]
        public System.DateTime date_delivered { get; set; }
    }
}
