//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectInformationManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public int user_id { get; set; }

        [DisplayName("First Name")]
        [Required(ErrorMessage = "Required.")]
        public string first_name { get; set; }

        [DisplayName("Last Name")]
        [Required(ErrorMessage = "Required.")]
        public string last_name { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "Required.")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Please enter a valid e-mail adress")]
        public string email { get; set; }

        [DisplayName("PI Name")]
        [Required(ErrorMessage = "Required.")]
        public string pi_name { get; set; }

        [DisplayName("Department")]
        [Required(ErrorMessage = "Required.")]
        public string department { get; set; }

        [DisplayName("Fund Number")]
        [Required(ErrorMessage = "Required.")]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "Fund number must be numeric value")]
        public int fund_number { get; set; }

        [DisplayName("Cost Center")]
        [Required(ErrorMessage = "Required.")]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "Cost center must be numeric value")]
        public int cost_center { get; set; }

        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Required.")]
        public string password { get; set; }

        [DisplayName("User Type")]
        [Required(ErrorMessage = "Required.")]
        public string user_type { get; set; }

    }
}
